<?php

namespace  App\Pos\Api\Filament\Resources;

use Filament\Forms\Form;
use Filament\Forms;
use Filament\Resources\Resource;
use Filament\Tables\Table;
use Filament\Tables;
use  App\Pos\Api\Filament\Resources\ApiResource\Pages\ManageAPIResource;

class ApiResource extends Resource
{
    protected static ?string $model = \ App\Pos\Api\Models\APIResource::class;

    protected static ?string $navigationIcon = 'heroicon-o-paper-airplane';

    public static function getNavigationGroup(): ?string
    {
        return "Settings"; // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return "APIs";
    }

    public static function getPluralLabel(): ?string
    {
        return "APIs";
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->description(fn(\ App\Pos\Api\Models\APIResource $resource) => $resource->slug)
                    ->searchable()
                    ->badge()
                    ->sortable(),
                Tables\Columns\TextColumn::make('method')
                    ->badge()
                    ->description(fn(\ App\Pos\Api\Models\APIResource $resource) => implode(', ', json_decode($resource->middleware)))
                    ->color(fn(\ App\Pos\Api\Models\APIResource $resource) => match ($resource->method) {
                        'GET' => 'success',
                        'POST' => 'info',
                        'PUT' => 'warning',
                        'PATCH' => 'orange',
                        'DELETE' => 'danger',
                        default => 'gray',
                    })
                    ->searchable()
                    ->sortable(),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('table')
                    ->label('Filter By Table')
                    ->searchable()
                    ->options(\ App\Pos\Api\Models\APIResource::query()->groupBy('table')->pluck('table', 'table')->toArray())
            ])
            ->defaultGroup('table');
    }

    public static function getPages(): array
    {
        return [
            'index' => ManageAPIResource::route('/'),
        ];
    }
}
